# Generated by Django 3.0.3 on 2020-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=13)),
                ('role_type', models.CharField(max_length=25)),
            ],
        ),
    ]
